server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  server:
    wait-time-in-ms-when-sync-empty: 3000      
      


